# Mines Bot Configuration File
# All settings can be overridden by command line arguments

# Access token (required)
access_token: "your_access_token_here"

# Betting settings
amount: 0.05              # Bet amount
currency: "trx"           # Currency: usdt, trx, doge, ltc, btc, eth, bch, xrp, eos, bnb
mines: 3                  # Number of mines (1-24)
shots: 5                  # Number of shots per game (1-20)

# Selection mode
mode: "smart"             # Field selection: row, random, smart, heatmap, pattern
retry: 3                  # Row retry count (for row mode only)
single_shot_mode: "win-stay"  # Single shot mode: fixed, win-return, win-stay, loss-switch

# Betting strategy
martingale: false         # Enable Martingale strategy
wins: 4                   # Consecutive wins to reset Martingale
multiplier: 4.0           # Martingale multiplier on loss
max_martingale: 10        # Max martingale levels before reset

# Win Step strategy (alternative to Martingale)
win_step: false           # Enable Win Step strategy
win_step_multiplier: 2.0  # Win Step multiplier
win_step_wins: 3          # Consecutive wins to reset to step 0

# Take profit
take_profit: 0            # Take profit target (0 = disabled)
